### PR TITLE
Merge joining network documents to reduce duplicated instructions

### PR DESCRIPTION
**Pull request by RogerKSI**

### CODE REVIEW

**Review by colmazia — COMMENTED** [review]
So should we add the snapshot docs from P’Nack to here as well before merging?

**Comment by RogerKSI** [comment]
> So should we add the snapshot docs from P’Nack to here as well before merging?

it merged in this already. You can see the main content of those PRs in `snapshot - chain layer`, `snapshot - HighStakes` section of joining mainnet page.

**Review by taobun — APPROVED** [review]
LGTM!

**Comment by taobun** [comment]
@babybunn Please recheck overall files na kub

**Review by babybunn — APPROVED** [review]

**Review by satawatnack — APPROVED** [review]

**Pull request merged**
